name: Propuesta de nuevo contenido
description: Proposición de nuevo contenido para el sitio WEB.
title: '[Publicación] Título de la publicación'
labels: ['content', 'triage']
body:
  - type: markdown
    id: introduction
    attributes:
      value: |
        **Contenido propuesto a publicar manteniendo el formato Markdown.**
        Antes de realizar una propuesta de contenido recuerde lo siguiente:
        - Leer la [Guía de Publicación para Colaboradores](https://github.com/yhojann-cl/ruta102.cl/blob/master/GUIDELINES.md).
        - Puedes proponer contenido desde una URL sin la necesidad de escribir todo su contenido si no tienes tiempo para ello pero consideras que es muy importante.
        ---
    validations:
      required: true
  - type: textarea
    id: content
    attributes:
      label: Contenido
      description: Contenido propuesto o detalle de la proposición de contenido.
    validations:
      required: true
  - type: textarea
    id: sources
    attributes:
      label: Fuentes
      description: Indique las fuentes del contenido propuesto si aplica.
    validations:
      required: false
  - type: input
    id: categories
    attributes:
      label: Categorías
      description: Categorías separados por coma.
    validations:
      required: true
