name: Propuesta de nuevo contenido
description: Proposición de nuevo contenido para el sitio WEB.
title: '[publicación] Título de la publicación'
labels: ['content', 'triage']
body:
  - type: markdown
    id: content
    attributes:
      value: |
        **Contenido propuesto a publicar manteniendo el formato Markdown.**
        Antes de realizar una propuesta de contenido recuerde lo siguiente:
        - El tipo de contenido debe estar acorde a los temas de Ruta102 sin offtopics.
        - Puedes proponer contenido desde una URL sin la necesidad de escribir todo su contenido si no tienes tiempo para ello pero consideras que es un contenido importante a considerar.
        - Se agradece la colaboración si se redacta todo contenido escrito en este issue.
        - Se agradece si se incluyen imagenes y se mantiene el orden de redacción.
        - Evitar el abuso de grocerias.
        ---
    validations:
      required: true
  - type: textarea
    id: sources
    attributes:
      label: Fuentes
      description: Indique las fuentes del contenido propuesto si aplica.
    validations:
      required: false
  - type: input
    id: categories
    attributes:
      label: Categorías
      description: Categorías separados por coma.
    validations:
      required: true
