name: Nuevo post de contenido
description: Nuevo post de contenido para el sitio WEB.
title: '[post] Título del post'
labels: ['content', 'triage']
body:
  - type: markdown
    id: introduction
    attributes:
      value: |
        **Contenido propuesto a publicar manteniendo el formato Markdown.**
        Antes de realizar una propuesta de contenido recuerde lo siguiente:
        - Leer la [Guía de Publicación para Colaboradores](https://github.com/yhojann-cl/ruta102.cl/blob/master/GUIDELINES.md).
        - Puedes proponer contenido desde una URL sin la necesidad de escribir todo su contenido si no tienes tiempo para ello pero consideras que es muy importante.
        - Todo contenido está sujeto a aprobación antes de ser publicado.
        - Recordar que los subtítulos son H3, o sea que en formato markdown son `###`.
        ---
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Resumen o sumario
      description: Resumen en pocas palabras, no más de 800 caracteres y sin imagenes.
    validations:
      required: true
  - type: textarea
    id: content
    attributes:
      label: Contenido
      description: Contenido completo o detalle del post.
    validations:
      required: true
  - type: textarea
    id: sources
    attributes:
      label: Fuentes
      description: Indique las fuentes del contenido si aplica.
    validations:
      required: false
  - type: input
    id: categories
    attributes:
      label: Categorías
      description: Categorías separados por coma.
    validations:
      required: true
